### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by fredj** [camptocamp/puppet-osrm#4]
- [x] shared memory `sysctl -w kernel.shmmax=2147483648`
- [ ] log rotate
- [x] log directory owner
- [ ] nagios checks (see https://github.com/rodo/nagios-plugins-osrm)
- [x] /etc/default/osrm-*
- [x] config file not read by /usr/bin/osrm-routed
- [x] add `-e 1` option in init.d
- [x] create `osrm` user and group
- [x] remove `templates/server.ini.erb`

**Comment by mcanevet** [comment]
@fredj @cjeanneret is this TODO list up to date?

**Comment by fredj** [comment]
List updated; it would be nice to have logrotate enabled for `/var/log/osrm/*.log`
